### ISSUE TITLE
Broken Link in Ex_01 - Word count.ipynb

### ISSUE THREAD

**Issue by PReichetanz** [cwf2/dices-examples#1]
Within the file `Ex_01 - Word count.ipynb`, the link to the `dices`-repository does not work.

The link is found in the following paragraph:
```
## Running the experiment

Here’s the code for calculating Achilles’ speech lengths by addressee.

### First, download the speeches

Using the API, we can search speeches using a set of key-value pairs [listed in greater detail here](https://cwf2.github.io/dices/2021/06/20/alpha.html).
```

I had a look into this repository as well but couldn't find to which file you refer.

PS: My best regards to Simone Finkmann, I am a former colleague from Rostock - now into Web Development but still very interested in what you are doing here!

**Comment by cwf2** [comment]
Thanks so much!
